image: registry.gitlab.com/couto/swiss-army-knife

stages:
  - dependencies
  - tests


dependencies:
  stage: dependencies
  script:
    - yarn install
    - yarn pack --filename swiss-army-knife.tgz
  artifacts:
    paths:
      - swiss-army-knife.tgz


eslint:
  stage: tests
  script:
    - tar -xzfv swiss-army-knife.tgz
    - yarn eslint

flow:
  stage: tests
  script:
    - tar -xzfv swiss-army-knife.tgz
    - yarn flow

unit:
  stage: tests
  script:
    - tar -xzfv swiss-army-knife.tgz
    - yarn test
