image: registry.gitlab.com/couto/swiss-army-knife

# Speed up Yarn instalation

before_script:
  - mkdir .tmp
  - export HOME="$(pwd)/.tmp"

cache:
  paths:
    - .tmp
    - node_modules/

# Set a plan
stages:
  - dependencies
  - tests


dependencies:
  stage: dependencies
  script:
    - yarn install
    - yarn pack --filename swiss-army-knife.tgz
  artifacts:
    paths:
      - swiss-army-knife.tgz

# Test Stage

eslint:
  stage: tests
  script:
    - tar -vxzf swiss-army-knife.tgz
    - yarn eslint

flow:
  stage: tests
  script:
    - tar -vxzfv swiss-army-knife.tgz
    - yarn flow

unit:
  stage: tests
  script:
    - tar -vxzfv swiss-army-knife.tgz
    - yarn test
