image: registry.gitlab.com/couto/swiss-army-knife

# Speed up Yarn instalation

before_script:
  - mkdir -p .tmp
  - export HOME="$(pwd)/.tmp"

cache:
  paths:
    - .tmp
    - node_modules/

# Set a plan
stages:
  - dependencies
  - tests
  - build


dependencies:
  stage: dependencies
  script:
    - yarn install

# Test Stage

eslint:
  stage: tests
  script:
    - yarn eslint

flow:
  stage: tests
  script:
    - yarn flow

unit:
  stage: tests
  script:
    - yarn test

# Build

compile:
  stage: build
  script:
    - yarn build
