image: registry.gitlab.com/couto/swiss-army-knife

cache:
  paths:
  - node_modules/

stages:
  - dependencies
  - tests

dependencies:
  stage: dependencies
  script:
    - yarn install
    - yarn pack --filename swiss-army-knife.tgz
  artifacts:
    paths:
      - swiss-army-knife.tgz

# Test Stage

eslint:
  stage: tests
  script:
    - tar -vxzf swiss-army-knife.tgz
    - yarn eslint

flow:
  stage: tests
  script:
    - tar -vxzfv swiss-army-knife.tgz
    - yarn flow

unit:
  stage: tests
  script:
    - tar -vxzfv swiss-army-knife.tgz
    - yarn test
